import os

SECRET_KEY = os.environ['SECRET_KEY']
DEBUG = True

DROPBOX_APP_KEY = os.environ['DROPBOX_APP_KEY']
DROPBOX_SECRET = os.environ['DROPBOX_SECRET']

SQLALCHEMY_DATABASE_URI = os.environ['SQLALCHEMY_DATABASE_URI']
SQLALCHEMY_ECHO = False

CALEPIN_ROOT = os.environ['CALEPIN_ROOT']
CALEPIN_THEME = os.environ['CALEPIN_THEME']
CALEPIN_ALLOW_EXTENSIONS = (u'.md', u'.json', u'.rst', u'html')
